const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
const FETCH_LOGIN_OUT = 'FETCH_LOGIN_OUT';

const FETCH_REQUEST_DATA = 'FETCH_REQUEST_DATA';
const FETCH_REQUEST_USER_DATA = 'FETCH_REQUEST_USER_DATA';
const UPDATE_USER_PHOTO = 'UPDATE_USER_DATA';
const ADD_FILE_STORAGE = 'ADD_FILE_STORAGE';

const SHOW_MODAL = 'SHOW_MODAL';

const CROPPER_ADD_PHOTO = 'CROPPER_ADD_PHOTO';
const CROPPER_ZOOM_PHOTO = 'CROPPER_ZOOM_PHOTO';

const SET_GPS_COORDINATES = 'SET_GPS_COORDINATES';
const SET_MAP_COORDINATES = 'SET_MAP_COORDINATES';
const SET_COUNT_MAP_ID = 'SET_COUNT_MAP_ID';

const SET_PHOTO_GALLERY = 'SET_PHOTO_GALLERY';
const REMOVE_ITEM_GALLERY = 'REMOVE_ITEM_GALLERY';

export {
  FETCH_LOGIN_SUCCESS,
  FETCH_LOGIN_ERROR,
  FETCH_LOGIN_OUT,
  FETCH_REQUEST_DATA,
  FETCH_REQUEST_USER_DATA,
  UPDATE_USER_PHOTO,
  ADD_FILE_STORAGE,
  SHOW_MODAL,
  CROPPER_ADD_PHOTO,
  CROPPER_ZOOM_PHOTO,
  SET_GPS_COORDINATES,
  SET_MAP_COORDINATES,
  SET_COUNT_MAP_ID,
  SET_PHOTO_GALLERY,
  REMOVE_ITEM_GALLERY
}