const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
const FETCH_LOGIN_OUT = 'FETCH_LOGIN_OUT';

const FETCH_REQUEST_DATA = 'FETCH_REQUEST_DATA';
const FETCH_REQUEST_USER_DATA = 'FETCH_REQUEST_USER_DATA';
const UPDATE_USER_PHOTO = 'UPDATE_USER_DATA';
const ADD_FILE_STORAGE = 'ADD_FILE_STORAGE';

const CROPPER_ADD_PHOTO = 'CROPPER_ADD_PHOTO';
const CROPPER_ZOOM_PHOTO = 'CROPPER_ZOOM_PHOTO';

const MODAL_OPENEND = 'MODAL_OPENEND';

const CORDS_FETCH_REQUESTED = 'CORDS_FETCH_REQUESTED';
const SET_MAP_COORDINATES = 'SET_MAP_COORDINATES';
const SET_MAP_ID = 'SET_MAP_ID';
const DELETE_MAP_COORDINATES = 'DELETE_MAP_COORDINATES';

const SET_PHOTO_GALLERY = 'SET_PHOTO_GALLERY';
const REMOVE_ITEM_GALLERY = 'REMOVE_ITEM_GALLERY';

const SET_NOTIFICATION = 'SET_NOTIFICATION';

export {
  FETCH_LOGIN_SUCCESS,
  FETCH_LOGIN_ERROR,
  FETCH_LOGIN_OUT,
  FETCH_REQUEST_DATA,
  FETCH_REQUEST_USER_DATA,
  UPDATE_USER_PHOTO,
  ADD_FILE_STORAGE,
  CROPPER_ADD_PHOTO,
  CROPPER_ZOOM_PHOTO,
  MODAL_OPENEND,
  CORDS_FETCH_REQUESTED,
  SET_MAP_COORDINATES,
  DELETE_MAP_COORDINATES,
  SET_MAP_ID,
  SET_PHOTO_GALLERY,
  REMOVE_ITEM_GALLERY,
  SET_NOTIFICATION
}